name: vip vegas
favicon: null
layout_spectrum: 0.15623
typography_spectrum: 0.7521
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#fefefe'
    - '#e89f68'
    - '#b5754f'
    - '#414548'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.8909155642613769
purpose: []
