name: vip vegas
favicon: null
layout_spectrum: 0.3617371376603842
typography_spectrum: 0.1032621746417135
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8092777824494988
  lightness: 0.07881624205037951
  saturation: 0.196624337695539
  rhythmicContrast: 0.8909155642613769
purpose: []
