name: vip vegas
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7521
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: vip vegas photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#fefefe'
    - '#e89f68'
    - '#b5754f'
    - '#414548'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.983871
  rhythmicContrast: 0.8909156
purpose: []
